name: Java CI & CD
on:
  push:
    # Add your branches here
    branches:
      - release
  pull_request:
    # Add your branches here
    branches:
      - release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle
      - name: Make Gradle Wrapper Executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./gradlew
      - name: Build Project
        run: ./gradlew clean build
  docker:
    runs-on: ubuntu-latest
    needs:
      - test
    # You will need to change this to your main branch that you want to build images from.
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: actions/checkout@v2
      - name: Make Gradle Wrapper Executable
        if: contains(matrix.os, 'win') == false
        run: chmod +x ./gradlew
      - name: Login to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}